apiVersion: v1
kind: Service
metadata:
  name: vcenter
  namespace: homelab
  annotations:
    tailscale.com/hostname: prism
    tailscale.com/tags: "tag:domain-lab-shortrib-net"
    tailscale.com/expose: "true"
spec:
  ports:
  - name: prism
    port: 9440
    protocol: TCP
    targetPort: 9440
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: prism
  namespace: homelab
  labels:
    kubernetes.io/service-name: prism
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 443
  - name: vami
    protocol: TCP
    port: 5480
endpoints:
  - addresses:
      - 10.18.1.240
    conditions:
      ready: true
