apiVersion: v1
kind: Service
metadata:
  name: malt
  namespace: homelab
  annotations:
    tailscale.com/hostname: malt
    tailscale.com/tags: "tag:domain-lab-shortrib-net"
    tailscale.com/expose: "true"
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: malt-slice
  namespace: homelab
  labels:
    kubernetes.io/service-name: malt  # Must match Service name
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - 10.18.1.220
    conditions:
      ready: true
