apiVersion: v1
kind: Service
metadata:
  name: vole
  namespace: homelab
  annotations:
    tailscale.com/hostname: vole
    tailscale.com/tags: "tag:domain-lab-shortrib-net"
    tailscale.com/expose: "true"
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin-console
    port: 30000
    protocol: TCP
    targetPort: 30000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vole-slice
  namespace: homelab
  labels:
    kubernetes.io/service-name: vole  # Must match Service name
addressType: IPv4
ports:
  - name: ssh
    protocol: TCP
    port: 22
  - name: https
    protocol: TCP
    port: 443
  - name: admin-console
    protocol: TCP
    port: 30000
endpoints:
  - addresses:
      - 10.24.9.10
    conditions:
      ready: true
