apiVersion: v1
kind: Service
metadata:
  name: marmot
  namespace: homelab
  annotations:
    tailscale.com/hostname: marmot
    tailscale.com/tags: "tag:domain-lab-shortrib-net"
    tailscale.com/expose: "true"
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin-console
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: admin-console-v3
    port: 30080
    protocol: TCP
    targetPort: 30080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: marmot-slice
  namespace: homelab
  labels:
    kubernetes.io/service-name: marmot  # Must match Service name
addressType: IPv4
ports:
  - name: ssh
    protocol: TCP
    port: 22
  - name: https
    protocol: TCP
    port: 443
  - name: admin-console
    protocol: TCP
    port: 30000
  - name: admin-console-v3
    protocol: TCP
    port: 30080
endpoints:
  - addresses:
      - 10.24.10.10
    conditions:
      ready: true
